version: '1'
services:
  microservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@eeg7gozk9ct7wyk1_low?TNS_ADMIN=/app/oracle_wallet/
      - spring.datasource.username=user_tienda_owner
      - spring.datasource.password=Owner#123456789
    restart: always